# Generated by Django 5.2.15 on 2026-06-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_code', models.CharField(max_length=20)),
                ('target_day', models.IntegerField()),
                ('window_before', models.IntegerField(default=0)),
                ('window_after', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_types', to='studies.study')),
            ],
            options={
                'unique_together': {('study', 'visit_code')},
            },
        ),
    ]
