# Generated by Django 5.2.10 on 2026-02-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=50)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('enrolled_at', models.DateField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='studies.study')),
            ],
            options={
                'unique_together': {('study', 'participant_code')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('baseline', 'Baseline'), ('month_3', 'Month 3'), ('year_1', 'Year 1')], max_length=20)),
                ('visit_date', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='participants.participant')),
            ],
            options={
                'ordering': ['visit_date'],
                'unique_together': {('participant', 'visit_type')},
            },
        ),
    ]
