# Generated by Django 5.2.10 on 2026-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['due_date']},
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_type',
            new_name='visit_code',
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('participant', 'visit_code')},
        ),
        migrations.AddField(
            model_name='visit',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='window_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='window_start',
            field=models.DateField(null=True),
        ),
    ]
