# Generated by Django 5.2.10 on 2026-04-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_visit_options_rename_visit_date_visit_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='deviation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
